### ISSUE TITLE
Training command with multi-GPU for CT-Clip Zero-shot model

### ISSUE THREAD

**Issue by qic999** [ibrahimethemhamamci/CT-CLIP#14]
Hi, thank you for your excellent work again! 
I would like to ask if the command for multi-GPU training is also `accelerate launch run_train.py`? And do you use a config for multi-GPU training?

**Comment by sezginerr** [comment]
We actually use FSDP for CLIP training, so the command is:

```
accelerate launch --use_fsdp run_train.py
```

However, it should theoretically work without FSDP, though I am not sure whether it would fit in the GPU memory. We did not use any config for Accelerate.

**Comment by qic999** [comment]
Thanks for your quick response!

**Comment by sezginerr** [comment]
Hi @qic999, please see #16 if you use fsdp.
