### ISSUE TITLE
CPU Memory size for loading total training data

### ISSUE THREAD

**Issue by qic999** [ibrahimethemhamamci/CT-CLIP#15]
Hi, thank you for your excellent work again!
I would like to ask how much cpu memory is required to load all the training data into memory? Did you load all 50k training data during the training process? Are there any training strategies that can reduce memory requirements?

**Comment by sezginerr** [comment]
Hi @qic999, torch dataloaders do not load all data simultaneously (unless you specifically load images in the dataset class during initialization). We add the paths to the images to a list, and then load them during training when a specific image is used. The memory requirement can increase with a higher number of workers in the dataloader (as it will load more samples in parallel), though. Unfortunately, I do not know the exact memory requirements during training, but 200GB should be sufficient for the current settings. If you need to reduce the GPU memory requirement, you can decrease the number of workers in the dataloader (but this will slow down the training).

**Comment by qic999** [comment]
@sezginerr Thanks for your answer!
